---
# Location where configuration files will be stored.
config_dir: '~'

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: America/Chicago
pihole_password: "change-this-password"
pihole_dnssec: true
pihole_rev_server: true
pihole_rev_server_target: "192.168.1.1"
pihole_rev_server_cidr: "192.168.1.0/24"
pihole_rev_server_domain: "lan"

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"

# Home assistant
home_assistant_enable: true

# Syncthing
syncthing_enable: true
