---
# handlers file for raspi
- name: Restart pi-hole
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pi-hole/"
    build: false
    restarted: true
  become: false
- name: Restart Home Assistant
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/home-assistant/"
    build: false
    restarted: true
  become: false
- name: Restart Syncthing
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/syncthing/"
    build: false
    restarted: true
  become: false
